apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
  namespace: memes
data:
  scylla.yaml: |
    cluster_name: scylla-cluster
    endpoint_snitch: GossipingPropertyFileSnitch
    listen_address: db-client-service
    rpc_address: db-client-service
    broadcast_address: a0742ee047729486fab8ef0acd36af80-685010908.us-east-1.elb.amazonaws.com 
    broadcast_rpc_address: a0742ee047729486fab8ef0acd36af80-685010908.us-east-1.elb.amazonaws.com
    seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
      - seeds: 35.196.103.17
  cassandra-rackdc.properties: |
    dc=aws
    rack=memes
