---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8ssandra-operator
  namespace: argocd
spec:
  destination:
    namespace: k8ssandra-operator
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://helm.k8ssandra.io/stable'
    targetRevision: v1.9.1
    chart: k8ssandra-operator
    helm:
      releaseName: k8ssandra-operator
      parameters:
        - name: controlPlane
          value: 'false'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
