apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: meme-db
  namespace: memes
  labels:
      app: memes
      app.kubernetes.io/name: memes
      app.kubernetes.io/instance: memes
      app.kubernetes.io/component: "db"
  annotations:
    configsync.gke.io/cluster-name-selector: demo-cassandra-gcp-cluster
spec:
  cassandra:
    serverVersion: "4.0.1"
    datacenters:
      - metadata:
          name: dc1
        size: 3
        storageConfig:
          cassandraDataVolumeClaimSpec:
            storageClassName: standard
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        config:
          jvmOptions:
            heapSize: 512M
        stargate:
          size: 1
          heapSize: 256M