apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
  namespace: memes
data:
  scylla.yaml: |
    cluster_name: scylla-cluster
    endpoint_snitch: GossipingPropertyFileSnitch
    listen_address: db-client-service
    rpc_address: db-client-service
    broadcast_address: 	35.196.103.17
    broadcast_rpc_address: 	35.196.103.17
    seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
      - seeds: 35.196.103.17
  cassandra-rackdc.properties: |
    dc=gcp
    rack=memes
