apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
  namespace: memes
data:
  scylla.yaml: |
    cluster_name: scylla-cluster
    endpoint_snitch: GossipingPropertyFileSnitch
    listen_address: db-client-service
    rpc_address: db-client-service
    broadcast_address: 20.231.244.71
    broadcast_rpc_address:  20.231.244.71
    seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
      - seeds: 104.196.100.128
  cassandra-rackdc.properties: |
    dc=azure
    rack=memes