
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cass-operator-webhook
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - cassandradatacenter-webhook-registration
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - update