
apiVersion: v1
kind: Service
metadata:
  labels:
      app: memes
      app.kubernetes.io/name: memes
      app.kubernetes.io/instance: memes
      app.kubernetes.io/component: "api"
  name: memes-api
  namespace: memes
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
      app: memes
      app.kubernetes.io/name: memes
      app.kubernetes.io/instance: memes
      app.kubernetes.io/component: "api"