apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBannedImageTags
metadata:
  name: ban-latest-tags
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["default","kube-system","cert-manager","k8ssandra-operator"]
  parameters:
    tags:
      - "latest"