apiVersion: v1
kind: Service
metadata:
  labels:
      app: memes
      app.kubernetes.io/name: memes
      app.kubernetes.io/instance: memes
      app.kubernetes.io/component: "ui"
  name: memes-ui
  namespace: memes
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 3000
  type: LoadBalancer
  selector:
    app: memes
    app.kubernetes.io/name: memes
    app.kubernetes.io/instance: memes
    app.kubernetes.io/component: "ui"
