apiVersion: v1
kind: Service
metadata:
  labels:
    name: cass-operator-webhook
  name: cassandradatacenter-webhook-service
  namespace: cass-operator
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    name: cass-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cass-operator
  namespace: cass-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cass-operator
  template:
    metadata:
      labels:
        name: cass-operator
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: cass-operator
        - name: SKIP_VALIDATING_WEBHOOK
          value: "FALSE"
        image: k8ssandra/cass-operator:v1.7.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - pgrep
            - .*operator
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        name: cass-operator
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/operator-sdk-ready
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsUser: 65534
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cass-operator-certs-volume
          readOnly: false
        - mountPath: /tmp/
          name: tmpconfig-volume
          readOnly: false
      serviceAccountName: cass-operator
      volumes:
      - emptyDir:
          medium: Memory
        name: tmpconfig-volume
      - name: cass-operator-certs-volume
        secret:
          secretName: cass-operator-webhook-config
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: cassandradatacenter-webhook-registration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: cassandradatacenter-webhook-service
      namespace: cass-operator
      path: /validate-cassandra-datastax-com-v1beta1-cassandradatacenter
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: cassandradatacenter-webhook.cassandra.datastax.com
  rules:
  - apiGroups:
    - cassandra.datastax.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cassandradatacenters
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10