apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-owner
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    excludedNamespaces: ["default","kube-system","cert-manager","argocd"]
  parameters:
    message: "All namespaces must have an `owner` label set"
    labels:
      - key: owner
        allowedRegex: "^[a-zA-Z]+.demo$"
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-purpose
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    excludedNamespaces: ["default","kube-system","cert-manager","argocd"]
  parameters:
    message: "All namespaces must have an `env` label set with a value from:  prod, dev, or stg"
    labels:
      - key: env
        allowedRegex: "^(dev|stg|prod)$"
